language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install sqlalchemy
# command to run tests
script:
  - mkdir db
  - curl https://github.com/chartes/adele/raw/master/adele.sqlite -o db/sqlite
  - python -m unittest utils/tests/test_alignment.py