language: python
python:
  - "3.5"

# command to install dependencies
install:
  - wget -N https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose
  - mkdir db && cd db
  - wget https://github.com/chartes/adele/blob/master/adele.sqlite?raw=true
  - cd ..
# command to run tests
script:
  - cd tests && nosetests --with-coverage --cover-package=app --cover-xml
after_success:
  - coverage combine
  - coveralls
