"""upgrade model with differentiated validation flags

Revision ID: 0de8c50c1a54
Revises: a4186aa68566
Create Date: 2020-01-27 15:09:07.969372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de8c50c1a54'
down_revision = 'a4186aa68566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commentary', schema=None) as batch_op:
        batch_op.create_unique_constraint('UniqueCommentaryType', ['doc_id', 'user_id', 'type_id'])

    with op.batch_alter_table('district', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_district_country_id_country'), 'country', ['country_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_commentaries_validated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_facsimile_validated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_notice_validated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_speechparts_validated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_transcription_validated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_translation_validated', sa.Boolean(), nullable=True))
        batch_op.drop_column('validation_step')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validation_step', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.drop_column('is_translation_validated')
        batch_op.drop_column('is_transcription_validated')
        batch_op.drop_column('is_speechparts_validated')
        batch_op.drop_column('is_notice_validated')
        batch_op.drop_column('is_facsimile_validated')
        batch_op.drop_column('is_commentaries_validated')

    with op.batch_alter_table('district', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_district_country_id_country'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'country', ['country_id'], ['id'])

    with op.batch_alter_table('commentary', schema=None) as batch_op:
        batch_op.drop_constraint('UniqueCommentaryType', type_='unique')

    # ### end Alembic commands ###
