"""Initial migration.

Revision ID: a4186aa68566
Revises:
Create Date: 2020-01-27 13:20:36.632766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4186aa68566'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('validation_step',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_document_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_role_name'), ['name'])

    with op.batch_alter_table('speech_part_type', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_speech_part_type_lang_code_language'), 'language', ['lang_code'], ['code'], ondelete='CASCADE')

    with op.batch_alter_table('transcription', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_user', ['doc_id', 'user_id'])

    with op.batch_alter_table('translation', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_user', ['doc_id', 'user_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('translation', schema=None) as batch_op:
        batch_op.drop_constraint('uix_user', type_='unique')

    with op.batch_alter_table('transcription', schema=None) as batch_op:
        batch_op.drop_constraint('uix_user', type_='unique')

    with op.batch_alter_table('speech_part_type', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_speech_part_type_lang_code_language'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'language', ['lang_code'], ['code'])

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_role_name'), type_='unique')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_document_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.alter_column('validation_step',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
